name = "Scrypt"
uuid = "2fdf5542-5ed4-5642-8140-83dcf60a5f79"
version = "0.2.1"
authors = ["Nicholas Bauer <nicholasbauer@outlook.com>"]

[deps]
Nettle = "49dea1ee-f6fa-5aa6-9a11-8816cee7d4b9"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[compat]
Nettle = "0.5"
SIMD = "3.2.1"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
